const chapters=[
["John to the Jordan: Source-Layer Orientation","约翰走向约旦河：来源层导览"],["Wilderness Life","旷野生活"],["Jordan and the Crowds","约旦河与人群"],["John's Social Ethics","约翰的社会伦理"],["Repentance, Fruit, and Judgment","悔改、果实与审判"],["The Stronger One Comes","那更有能力者将来"],
["Jesus Walks Toward the Jordan","耶稣走向约旦河"],["Mark: Earliest Extant Baptism Narrative","马可：最早现存的受洗叙事"],["Matthew: John's Objection Added","马太：加入约翰的反对"],["Luke: The Baptizer Recedes","路加：施洗者退到幕后"],["John: Baptism Reframed as Witness","约翰：受洗被重构为见证"],
["John's Disciples","约翰的门徒"],["Jesus' Disciples","耶稣的门徒"],["Baptism and Purification Dispute","施洗与洁净之争"],["He Must Increase","他必兴旺"],["John Challenges Herod","约翰挑战希律"],["Imprisonment","监禁"],["Are You the Coming One?","那将要来的是你吗？"],["Jesus Answers with Deeds","耶稣以行动回应"],["Jesus Evaluates John","耶稣评价约翰"],["Gospel Death Tradition","福音书中的死亡传统"],["Josephus: Political Threat Account","约瑟夫斯：政治威胁叙事"],["John's Disciples Bury Him","约翰的门徒埋葬他"],["Jesus Hears the News","耶稣听见消息"],
["After John Was Handed Over","约翰被交出去之后"],["The Kingdom Has Drawn Near","天国临近"],["Healing","医治"],["Table Fellowship with the Excluded","与被排斥者同席"],["Forgiveness","赦免"],["Sabbath","安息日"],["Seed and Sowing","种子与撒种"],["Storm and Fear","风暴与恐惧"],["Bread and Sharing","饼与分享"],["Power and Service","权力与服事"],["Entering Jerusalem","进入耶路撒冷"],["Death and Empty Tomb","死亡与空墓"],
["Witness to the Light","为光作见证"],["Living Water","活水"],["Bread of Life","生命之粮"],["Light of the World","世界的光"],["Good Shepherd","好牧人"],["The Vine","葡萄树"],["Love One Another","彼此相爱"],["Peace Be with You","愿你们平安"]];
const phases=[
{range:"01–06",en:"THE WITNESS",zh:"见证者",descEn:"John appears, calls, cleanses, confronts, and points beyond himself.",descZh:"约翰出现、呼召、洁净、挑战权力，并指向那在他之后的人。"},
{range:"07–15",en:"THE WATER",zh:"水",descEn:"Jesus enters John's river; four Gospel tellings are kept distinct.",descZh:"耶稣进入约翰的河流；四部福音书的叙述被分别看见。"},
{range:"16–24",en:"THE COST OF WITNESS",zh:"见证的代价",descEn:"John challenges power, questions from prison, dies, and hands the story forward.",descZh:"约翰挑战权力、在监狱中发问、死亡，并把故事交向前方。"},
{range:"25–36",en:"THE WAY OPENS",zh:"道路展开",descEn:"Jesus' mission after John's arrest follows the earliest extant Markan spine.",descZh:"约翰被捕之后，耶稣的使命沿最早现存的马可叙事展开。"},
{range:"37–44",en:"LIGHT & LOVE",zh:"光与爱",descEn:"The later Johannine theological expansion arrives last and is labeled honestly.",descZh:"较晚的约翰神学展开最后抵达，并被诚实地标注。"}];
let language=localStorage.getItem("fjtj-language")||(navigator.language.toLowerCase().startsWith("zh")?"zh":"en");
function renderDynamicCopy(){document.querySelector("#roadmap").innerHTML=phases.map((phase,index)=>`<article><div class="phase">0${index+1}</div><p class="range">CH. ${phase.range}</p><h3>${language==="zh"?phase.zh:phase.en}</h3><p>${language==="zh"?phase.descZh:phase.descEn}</p></article>`).join("");document.querySelector("#chapter-list").innerHTML=chapters.map((chapter,index)=>`<li><span>${String(index+1).padStart(2,"0")}</span><b>${language==="zh"?chapter[1]:chapter[0]}</b></li>`).join("")}
function setLanguage(next){language=next;document.documentElement.dataset.lang=next;document.documentElement.lang=next==="zh"?"zh-CN":"en";document.querySelectorAll("[data-set-lang]").forEach(button=>button.setAttribute("aria-pressed",String(button.dataset.setLang===next)));localStorage.setItem("fjtj-language",next);renderDynamicCopy()}
document.querySelectorAll("[data-set-lang]").forEach(button=>button.addEventListener("click",()=>setLanguage(button.dataset.setLang)));setLanguage(language);
document.querySelector("#interest-form").addEventListener("submit",event=>{event.preventDefault();const form=new FormData(event.currentTarget);const email=form.get("email");const name=form.get("name")||"—";const interests=form.getAll("interest").join(", ")||"Project updates";const subject=language==="zh"?"加入 From John to Jesus 创始读者名单":"Join the From John to Jesus founding readers";const body=language==="zh"?`Joyce 你好，\n\n我希望加入 From John to Jesus 创始读者名单。\n\n名字：${name}\n邮箱：${email}\n感兴趣：${interests}\n\n请在第一章预览或扑克预售开放时通知我。`:`Hi Joyce,\n\nI would like to join the From John to Jesus founding readers.\n\nName: ${name}\nEmail: ${email}\nInterested in: ${interests}\n\nPlease notify me when the Chapter 1 preview or deck pre-sale is available.`;document.querySelector("#form-status").textContent=language==="zh"?"正在打开邮件应用，请发送已生成的申请邮件。":"Opening your email app—please send the prepared request.";window.location.href=`mailto:joyce@ggcgames.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});
